/-
In Lean, every concrete type other than the universes and evry type constructor other than dependent
arrows is an instance of a general family of type constructions known as inductive types.
It is possible to construct a substantial edifice of mathematics based on nothing more than the
type universes, dependent arrow types, and inductive types; everything else follows from those.

An inductive type is built up from a specified list of constructors. In Lean, the syntax for specifying
such a type is as follows:

inductive Foo where
          | constructor₁ : ... → Foo
          | constructor₂ : ... → Foo
          ...
          | constructorₙ : ... → Foo

Inuitively, each constructor specifies a way of building new objects of Foo, possibly from previously
constructed values. The type Foo consists of nothing more than the objects that are constructed this
way

Arguments of the constructors can include objects of type Foo, subject to a
certain positivity constraint, which guarantees that the elements of Foo
are built from the bottom up.

Every inductive type comes with introduction rules, which show how to construct
an element of the type, and elimination rules, which show how to "use" an
element of the type in another construction

Intro rules for an inductive type are just constructors that are specified in
the definition of the type, and elimination rules provide a principle for
recursion on the type, which includes, in a special case, a principle of
induction
-/

/- 7.1 Enumerated Types -/
inductive Weekday where
          | sunday    : Weekday
          | monday    : Weekday
          | tuesday   : Weekday
          | wednesday : Weekday
          | thursday  : Weekday
          | friday    : Weekday
          | saturday  : Weekday

/- the inductive command creates a new type, Weekday -/
#check Weekday.sunday
#check Weekday.monday

section
open Weekday
#check sunday
#check monday
end

/- You could also omit the type annotation -/
/-
Th elimination principle, Weekday.rec, is defined along with the type Weekday
and its constructors, AKA a recursor, and it is what makes the type
"inductive":

It allows us to define a function on Weekday by assigning values corresponding to
each constructor. The intuition is that an inductive type is exhaustively
generated by the constructors, and has no elements beyond those they construct
-/
#check Weekday.rec

/-
We will use match to define a function from Weekday → Nat
-/
section
open Weekday

def numberOfDay (d : Weekday) : Nat :=
    match d with
    | sunday    => 1
    | monday    => 2
    | tuesday   => 3
    | wednesday => 4
    | thursday  => 5
    | friday    => 6
    | saturday  => 7

#eval numberOfDay sunday
#eval numberOfDay monday
#eval numberOfDay tuesday

def next (d : Weekday) : Weekday :=
  match d with
  | sunday    => monday
  | monday    => tuesday
  | tuesday   => wednesday
  | wednesday => thursday
  | thursday  => friday
  | friday    => saturday
  | saturday  => sunday

def previous (d : Weekday) : Weekday :=
  match d with
  | sunday    => saturday
  | monday    => sunday
  | tuesday   => monday
  | wednesday => tuesday
  | thursday  => wednesday
  | friday    => thursday
  | saturday  => friday

theorem next_previous (d : Weekday) : next (previous d) = d := by
        cases d <;> rfl
end
